#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

# runApplication $application

runApplication decomposePar -force
runParallel $application
runApplication reconstructPar
runApplication foamToVTK


#------------------------------------------------------------------------------
